### ISSUE TITLE
Darkmode visual issues

### ISSUE THREAD

**Issue by ditto13** [FlavienBusseuil/bga-chrome-extension#59]
Just started using this extension and it's awesome!  However, noticing some minor visual things with relation to the darkmode setting.
(I originally thought it was BGA change, and didn't realize it was this extension :) So I added a bug on BGA: #95669 see it for additional info )

1) the animated hourglass showing somebody's turn, is difficult to see in darkmode.
2) text (ie in bug list) is black on black ..
3) during a game which requires you to select another player (eg Regicide after playing Jester, Not Alone when choosing a hunted, etc.) , the visual to show which player has been selected is not visible (see screen shots).

[imgur.com/fR8H2pq](https://imgur.com/fR8H2pq)
[imgur.com/nHVqZ9e](https://imgur.com/nHVqZ9e)

**Comment by FlavienBusseuil** [comment]
@ditto13 thanks for your feedbacks !
@cdelaforge you may have a look whenever it suits you :+1:

**Comment by cdelaforge** [comment]
Thanks for the feedback :)
The first point should already be fixed. Could you confirm ?
The second point will be fixed in next published version (after the google validation)
I will have a look for the third point, actually the biggest part of the job is to test each game one by one and make specific corrections if necessary.

**Comment by ditto13** [comment]
Fluxx: card text is while , card background is white.  O.o (guessing this might be clashing with the assumption we have a dark background ;) )

**Comment by ditto13** [comment]
In the Games page, My favourites ... eah game has text below it showing turn based vs real time, and what options are set.  With darkmode, it's not very visible.

https://imgur.com/a/pb3m2Jz

**Comment by ditto13** [comment]
When opening a hotseat game, the text to enter a name is light grey on white .. visible, but hard to see (minor . but hey ;) )

https://imgur.com/a/vyXv2gQ

**Comment by cdelaforge** [comment]
thanks! let's fix all this :)
