### ISSUE TITLE
Show friends games that are available to join

### ISSUE THREAD

**Issue by michael1w** [FlavienBusseuil/bga-chrome-extension#63]
Please consider listing open friends or group tables that are available for you to join, on the tables list.

It is very difficult on the BGA website to join a friend's game.

When you create a game and want to play with friends or a group, you can restrict who can join the table to friends or a group. 
Then the idea is that you leave it up to your friends to join - you don't have to manage asking and inviting each friend... But this is very difficult! You need to search every different board game type in the lobby to see if your friends have set up a table of that kind of game with an open spot for you to join.

See the issue raised here - https://boardgamearena.com/bug?id=23285

**Comment by cdelaforge** [comment]
Feature available
