### ISSUE TITLE
Dark mode inactive buttons still show blue instead of grey

### ISSUE THREAD

**Issue by rstanculescu** [FlavienBusseuil/bga-chrome-extension#70]
Lately the inactive buttons show blue (active) instead of grey (inactive) when using dark mode. If I switch to light mode everything looks fine. This happens at least in Terraforming Mars. I think I've seen it in some other games, but don't remember right now. I will update the issue when I find others.

**Comment by cdelaforge** [comment]
The issue should be fixed now, could you please confirm?

**Comment by rstanculescu** [comment]
Yeap, looks good now.
--
Radu Stanculescu
