### ISSUE TITLE
Dark mode for archived games & tutorials

### ISSUE THREAD

**Issue by yzemaze** [FlavienBusseuil/bga-chrome-extension#71]
What’s the reasoning behind the unavailability of dark mode for archived games and tutorials?
https://github.com/FlavienBusseuil/bga-chrome-extension/blob/c8392c137c512a3153b823f7a6adc2abf7df5ac5/src/js/ui/content/darkMode/darkStyleFunctions.ts#L17-L19

**Comment by cdelaforge** [comment]
Hello,
Simply because the extension relies on the game name in the URL to apply game-specific CSS code.
That said, it's still on my road-map, I just need a little time.

**Comment by cdelaforge** [comment]
Dark mode for archived games and tutorials added in version 1.10.4
