### ISSUE TITLE
"Block content on any page" permission

### ISSUE THREAD

**Issue by electrofloat** [FlavienBusseuil/bga-chrome-extension#76]
Hi!

Your firefox extension here:
https://addons.mozilla.org/en-US/firefox/addon/board-game-arena-bga-extension/

asks for permission to: "Block content on any page".

Surely, this should be fixed, because noone would install an extension that can block content on any page.

Maybe this helps?: https://stackoverflow.com/questions/77196167/chrome-extenshion-block-content-on-any-page-warning

**Comment by cdelaforge** [comment]
There are in fact around 2,000 weekly users (all browsers combined), so some people don't ask themselves as many questions as you do :) 
But you're absolutely right, it's a mistake, I didn't know “declarativeNetRequestWithHostAccess” and I was using “declarativeNetRequest” wrongly.
This will be corrected in the next version.
Thanks a lot! I hope you will like the extension ;)

**Comment by cdelaforge** [comment]
The version 1.10.17 is available for Firefox.
Don't hesitate to let me know what you think of the extension once you've tested it :)
